# Generated by Django 3.2.5 on 2021-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.PositiveSmallIntegerField(blank=True)),
                ('protein', models.PositiveSmallIntegerField(blank=True)),
                ('dietary_note', models.ManyToManyField(blank=True, related_name='Food', to='diets.Diet')),
            ],
        ),
    ]
