# Generated by Django 3.2.5 on 2021-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('diets', models.ManyToManyField(related_name='foods', to='diets.Diet')),
            ],
        ),
    ]
