# Generated by Django 3.2.5 on 2021-07-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='dietary_note',
            new_name='diets',
        ),
    ]
