# Generated by Django 3.2.5 on 2021-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        ('foods', '0004_alter_food_diets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='diets',
            field=models.ManyToManyField(related_name='foods', to='diets.Diet'),
        ),
    ]
