# Generated by Django 3.2.5 on 2021-07-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_diets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
    ]
