# Generated by Django 3.2.5 on 2021-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_remove_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='banana', max_length=50),
            preserve_default=False,
        ),
    ]
