# Generated by Django 3.2.5 on 2021-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dietary_requirements',
            field=models.ManyToManyField(related_name='User', to='diets.Diet'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Gluten Free', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
