# Generated by Django 3.2.5 on 2021-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        ('jwt_auth', '0003_auto_20210722_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dietary_requirements',
            field=models.ManyToManyField(blank=True, related_name='User', to='diets.Diet'),
        ),
    ]
